version: '3.7'

services:
  web:
    build: .
    command: ./out/main 
    volumes:
      - .:/app 
    ports:
      - 4000:4000 
    depends_on:
      - db

  db:
    image: postgres:11
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data/

volumes: 
  postgres_data: